### ISSUE TITLE
what happened to downgrading below 53 

### ISSUE THREAD

**Issue by unboker002** [e9x/chrome100#10]
I have an old chromebook from 2014 and i looked at chrome100.dev a long time ago and there was a recovery image for version 33 but it is not there anymore

**Comment by e9x** [comment]
> I have an old chromebook from 2014 and i looked at chrome100.dev a long time ago and there was a recovery image for version 33 but it is not there anymore

You're right, we're missing many earlier versions. I will look into this.

**Comment by e9x** [comment]
See https://github.com/e9x/chrome-versions/commit/a36111d50f4012a132bb502df054a0c312c4324a and 477c8bdbeda76969fc2a03402cb9bddebf947d70. This is fixed.
