### ISSUE TITLE
[Suggestion] add alternative flashing methods to /guide

### ISSUE THREAD

**Issue by joebobbio** [e9x/chrome100#3]
The Chromebook Recovery tool has gotten pretty bad as of late - it's best to use something like Rufus on Windows or `dd` on Mac/Linux (never set `bs` parameter when using `dd`, it may cause the recovery verification to fail)

**Comment by e9x** [comment]
This is true. I've been flashing my recovery images to my USBs with DD ever since I switched to Linux.

**Comment by e9x** [comment]
added in b13940cf7884d4ecdb3554768daa72eaea6f8c5d
