### ISSUE TITLE
Current prod broken

### ISSUE THREAD

**Issue by luphoria** [e9x/chrome100#5]
The current production build (https://chrome100.dev) is messed up.
- No clue what the cause is, but every hyperlink click seems to delay by several seconds.
- Styling on /info, /guide is broken. You can see that webpacked files are returning 404.

**Comment by luphoria** [comment]
Throwing idea at the wall: fb6f1a06fccdb868c9cb001dc1f0ce28fac5d06b seems to be the commit where it broke. Try reverting this.

**Comment by e9x** [comment]
> The current production build (https://chrome100.dev) is messed up.

Just confirmed, this is indeed an issue. I just rebuilt the frontend on the server and it appears to be working now.

**Comment by luphoria** [comment]
Working for me too. Reopen this issue if there seems to be something consistently borking in the build process.
