### ISSUE TITLE
question (ignore if not owner)

### ISSUE THREAD

**Issue by jmd-school** [e9x/chrome100#6]
is your real name Aayan?

**Comment by e9x** [comment]
No. This isn't a channel for anything personal. If you have contact to me directly, use that instead of GitHub.

**Comment by e9x** [comment]
> > use that instead of GitHub.
> 
> You never specified `that`

I meant whatever they can find to contact me. It is ambiguous. If they cannot contact me, then I would prefer it remain that way.
