### ISSUE TITLE
Option/default to search version => board (instead of board => version)

### ISSUE THREAD

**Issue by luphoria** [e9x/chrome100#8]
This is something I for some reason hadn't thought of, but for normal users it would make so much more sense than the current setup.
Currently, users have to find their board, before they find their version. But this honestly seems pretty backwards.
I propose instead, Chrome100 lists every major version (ie first number, 107, 106, 105, ..., 60, 59, 58). And when you click that version, you select your board, and it shows you the closest version(s) (maybe you could carousel of sorts left and right). 
In general, the chrome100 indexing page should be refactored because it's sluggish and not user-friendly on top of it.

**Comment by joebobbio** [comment]
I disagree - it's like this on basically every Chrome OS recovery index, such as [cros.tech](https://cros.tech) and [Google's own](https://chromiumdash.appspot.com/serving-builds?deviceCategory=ChromeOS). Swapping the pages will likely make it more confusing as it's different than any other index on the Internet right now

**Comment by e9x** [comment]
Never posted an update on this outside of DMs.
Here is what it might look like:
Homepage:
![Screenshot_20221217_151020](https://user-images.githubusercontent.com/76465669/208264428-a8d7b079-4b19-46a4-821a-1be085b9eacc.png)
Version view:
![Screenshot_20221217_151046](https://user-images.githubusercontent.com/76465669/208264436-eaf03f4c-bbd4-4b95-875f-fb2fd9cf26eb.png)
Board view:
![Screenshot_20221217_151059](https://user-images.githubusercontent.com/76465669/208264444-bb481495-d7c0-41bc-97cf-9bd79674dc96.png)

I'm not feeling the design.

**Comment by luphoria** [comment]
I like it, although the design could be improved.
I think you're both right though. Normal setup works just fine as is.
