### ISSUE TITLE
Grunt v87 found, but unlisted

### ISSUE THREAD

**Issue by vukle** [e9x/chrome100#9]
Hey, just found v87 for grunt. No clue why it isn't listed but heres the platform version.
`13505.73.0`

**Comment by vukle** [comment]
v6 btw

**Comment by e9x** [comment]
Do you have a full link to the recovery image? The platform alone won't do.

**Comment by BinBashBanana** [comment]
Here's the link for grunt:
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13505.73.0_grunt_recovery_stable-channel_mp-v6.bin.zip
this version also appears to exist for terra:
https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13505.73.0_terra_recovery_stable-channel_mp-v2.bin.zip

**Comment by BinBashBanana** [comment]
Also keep an eye out for the "brask" board which should have recovery images appearing soon.

**Comment by BinBashBanana** [comment]
Update: it's out today: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15236.66.0_brask_recovery_stable-channel_mp-v3.bin.zip
@e9x

**Comment by e9x** [comment]
@BinBashBanana Thank you. What's interesting is how the scraper didn't catch 13505.73.0. I want to be thorough and add to the sources so these builds and possibly more are automatically picked up, however I can modify the scripts and create a manual list.

**Comment by e9x** [comment]
This may be related to #10, however 13505.73.0 is still not being picked up even after all the fixes.

**Comment by e9x** [comment]
I've identified this build as v87.0.4280.109.

**Comment by BinBashBanana** [comment]
New "nissa" board is out now as well: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15236.80.0_nissa_recovery_stable-channel_mp-v2.bin.zip
